name: CI

on:
  
  
  workflow_dispatch:
    inputs:
      Release:
        type: boolean
        description: Release

jobs:
  build:

    runs-on: ubuntu-latest
           
    steps:
    - uses: actions/checkout@v1
    
    
    - name: echo install
      run: |
        echo "${{ inputs.Release }}"
